### ISSUE TITLE
subscribe error

### ISSUE THREAD

**Issue by jiujiucheng** [qishibo/redis#2]
## PHP Warning 'yii\base\ErrorException' with message 'crc32() expects parameter 1 to be string, array given'

in redis/src/Hash/Consistant.php:

` ``
/**
     * lookup the right node by key
     *
     * @param      string  $key    redis key
     *
     * @return     string  server node
     */
    public function lookUp($key)
    {
        $this->checkSortNode();
        $keyPosition = $this->keyCalculator->calc($key);
        ....
    }
```

**Comment by qishibo** [comment]
emmm, Can you give me your execution context

**Comment by qishibo** [comment]
I guess the key you passed is an array
